name: build-actions
on: [push]
jobs:
  run-hardnat-build-command:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npx hardhat run scripts/deploy.js --network kovan