name: build-actions
on: [push]
jobs:
  run-hardnat-build-command:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
      - run: npm install --save-dev
      - run: npx hardhat run scripts/deploy.js --network kovan